import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="w-full min-h-screen flex flex-col items-center justify-center">
      <Head>
        <title>Next Tailwindcss Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>template</p>
    </div>
  )
}

export default Home
